"""
Data schema definitions for normalized job rows.

The `JobRow` dataclass defines the fields expected in the
`jobs.csv` output.  Fields correspond to those described in the
README under "Data Schemas".  Optional fields are annotated with
`Optional[...]` to allow missing values.  Lists are used for multi
valued fields like `locations`.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Optional


@dataclass
class JobRow:
    """Structured representation of a job posting.

    Attributes:
        job_id: Internal identifier for the job.  This may be
            generated by the crawler or derived from the provider.
        company: Company name.
        source: Name of the ingestion source (e.g. "greenhouse", "lever").
        ext_id: External identifier provided by the source platform.
        title: Job title.
        department: Department or team name, if available.
        employment_type: Full‑time, part‑time, contract, etc.
        locations: List of location strings.  Must include 'Remote'
            when remote work is allowed.
        remote_flag: Whether the job allows remote work.
        onsite_flag: Whether the job requires on‑site presence.
        pay_min: Minimum annual salary or hourly rate.
        pay_max: Maximum annual salary or hourly rate.
        pay_currency: Currency code for the pay range.
        posted_date: ISO‑formatted date when the job was posted.
        updated_at: ISO‑formatted date when the job was last updated.
        absolute_url: Canonical URL to the job posting.
        description_text: Plain text description of the role.
        description_html: Raw HTML description of the role.
        scraped_at: Timestamp when the job was scraped.
        source_fingerprint: Unique fingerprint (e.g. hash) of the
            source HTML used to detect duplicates.
    """

    job_id: str
    company: str
    source: str
    ext_id: str
    title: str
    department: Optional[str] = None
    employment_type: Optional[str] = None
    locations: List[str] = field(default_factory=list)
    remote_flag: bool = False
    onsite_flag: bool = False
    pay_min: Optional[float] = None
    pay_max: Optional[float] = None
    pay_currency: Optional[str] = None
    posted_date: Optional[str] = None
    updated_at: Optional[str] = None
    absolute_url: str = ""
    description_text: str = ""
    description_html: str = ""
    scraped_at: str = ""
    source_fingerprint: str = ""